config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :load_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created succesfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if  @article.update(article_params)
      flash[:notice] = "Article was updated succesfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted succesfully."
    redirect_to articles_path
  end

  private

  def load_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container-sm">
  <%= render 'shared/errors', errors: @article.errors %>
  <div class="card bg-primary bg-gradient shadow mt-4">
    <%= form_with(model: @article, local: true) do |f| %>
      <div class="card-body">
        <div class="form-group row mb-3">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: " form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group row mb-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="form-group row">
          <%= f.submit class:"btn btn-outline-light btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="text-center mt-4 mb-4">
    <%= link_to 'Cancel and return to articles listing', articles_path, class: "text-primary " %>
  </div>  
</div>

app/views/articles/_preview.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow ">
      <div class="card-header fst-italic">by John</div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to article.title, article, class: "text-success" %></h5>
        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
        <%= link_to "View", article, class:"btn btn-outline-success" %>
        <%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-info" %>
        <%= button_to "Delete", article_path(article), method: :delete, class:"btn btn-outline-danger", onclick: "return confirm('Are you sure?')", form: { class: "d-inline"} %>
      </div>
      <div class="card-footer text-muted">
        <small>
          Created <%= time_ago_in_words(article.created_at) %> ago
          <% unless article.created_at == article.updated_at %>
          ,edited <%= time_ago_in_words(article.updated_at) %> ago
          <% end %>
        </small>      
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit Article</h1>

<%= render 'articles/form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<div class="text-end">
<%= link_to 'Create new article', new_article_path, class: 'btn btn-primary btn-sm' %>
</div>

<div class="container">
  <% @articles.each do |article| %>
    <%= render 'articles/preview', article: article %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 mb-4">Create a new Article</h1>

<%= render 'articles/form' %>

app/views/articles/show.html.erb
<div class="container-sm mb-4">
  <h1 class="text-center mt-4 mb-4"><%= @article.title %></h1>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow ">
        <div class="card-header fst-italic">by John</div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info" %>
          <%= button_to "Delete", article_path(@article), method: :delete, class:"btn btn-outline-danger", onclick: "return confirm('Are you sure?')", form: { class: "d-inline"} %>
        </div>
        <div class="card-footer text-muted">
          <small>
            Created <%= time_ago_in_words(@article.created_at) %> ago
            <% unless @article.created_at == @article.updated_at %>
              | edited <%= time_ago_in_words(@article.updated_at) %> ago
            <% end %>
          </small>      
        </div>
      </div>
    </div>
  </div>
  <div class="text-center mt-4">
    <%= link_to 'Cancel and return to articles listing', articles_path, class: "text-primary " %>
  </div>  
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
  <div class="container mt-2 mb-2">
    <% flash.each do |name, message| %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary  navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to 'Blog', root_path, class:'navbar-brand', id: 'logo' %>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Articles', articles_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class:'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>  
  </head>

  <body class="d-flex flex-column min-vh-100 bg-secondary bg-gradient">

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="flex-grow-1">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
<h1>This is the home page</h1>

app/views/shared/_errors.html.erb
<% if errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    <h4 class="alert-heading">The following errors prevents the article from being saved</h4>
    <ul>
    <% errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>